name: sentry
version: '9.0'
summary: Sentry is a modern error logging and aggregation platform
description: |
  Sentry’s real-time error tracking gives you insight
  into production deployments and information to reproduce
  and fix crashes.
grade: stable
confinement: strict

architectures:
  - build-on: i386
  - build-on: amd64

apps:
  sentry:
    command: sentry
    plugs:
      - home
      - network
      - network-bind
  web:
    command: sentry run web
    daemon: simple
    plugs:
      - home
      - network
      - network-bind
  worker:
    command: sentry run worker
    daemon: simple
    environment:
      C_FORCE_ROOT: 1
    plugs:
      - home
      - network
      - network-bind
  cron:
    command: sentry run cron
    daemon: simple
    plugs:
      - home
      - network
      - network-bind

parts:
  sentry:
    plugin: python
    python-version: python2
    python-packages:
      - sentry==$SNAPCRAFT_PROJECT_VERSION
      - sentry-plugins==$SNAPCRAFT_PROJECT_VERSION
      - https://github.com/getsentry/sentry-auth-saml2/archive/master.zip
      - https://github.com/getsentry/sentry-auth-github/archive/master.zip
    build-packages:
      - libssl-dev
      - libffi-dev
      - libjpeg-dev
      - libpq-dev
      - python-dev
      - clang
      - build-essential
      - libxmlsec1-dev
      - cargo
