name: sentry
version: '21.5.0'
epoch: 1*
summary: Sentry is a modern error logging and aggregation platform
description: |
  Sentry’s real-time error tracking gives you insight
  into production deployments and information to reproduce
  and fix crashes.
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: i386
  - build-on: amd64

plugs:
  shared-memory:
    private: true

apps:
  sentry:
    command: bin/sentry
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - network-bind
  web:
    command: bin/sentry run web
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    daemon: simple
    plugs:
      - home
      - network
      - network-bind
  worker:
    command: bin/sentry run worker
    daemon: simple
    environment:
      C_FORCE_ROOT: 1
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - network-bind
  cron:
    command: bin/sentry run cron
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    daemon: simple
    plugs:
      - home
      - network
      - network-bind

parts:
  sentry:
    plugin: python
    python-packages:
      - wheel==0.36.2
      - requests==2.20.0
      - xmlsec==0.6.1
      - python-u2flib-server==5.0.1
      - pyrsistent==0.17.3
      - grpcio==1.35.0
      - phabricator==0.6.1
      - maxminddb==1.5.4
      - petname==2.6
      - simplejson==3.11.1
      - hiredis==0.3.1
      - PyYAML==5.3.1
      - mmh3==2.3.1
      - urllib3==1.24.2
      - setproctitle==1.1.9
      - uwsgi==2.0.19.1
      - parsimonious==0.8.0
      - grpc-google-iam-v1==0.12.3
      - googleapis-common-protos==1.52.0
      - python3-saml==1.4.0
      - sentry==$SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - libssl-dev
      - libffi-dev
      - libjpeg-dev
      - libpq-dev
      - clang
      - build-essential
      - libxmlsec1-dev
      - cargo
      - pkg-config
      - python3.6-dev
      - python3-pip
      - python3-venv
      - libpython3-all-dev
    build-environment:
      - CPPFLAGS: '$CPPFLAGS -I/usr/include/python3.6m'
      - CFLAGS: "$CFLAGS -I/usr/include/python3.6m"
    stage-packages:
      - libicu60
      - libpython3.6
      - libxml2
      - libxmlsec1
      - libxmlsec1-openssl
      - libxslt1.1

