#!/bin/bash
set -u
set -o pipefail
# Try to ensure we have config first
$SNAP/command-sentry.wrapper config list >/dev/null 
if [ $? -eq 0 ]; then $SNAP/command-sentry.wrapper upgrade --noinput; else echo "Missing config, doing nothing"; fi
